receivers:
  otlp:
    protocols:
      http:
exporters:
  logging:
    loglevel: warn
  otlp:
    endpoint: http://tempo:4317
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
