FROM node:20-alpine AS deps
RUN corepack enable && corepack prepare pnpm@9.9.0 --activate
WORKDIR /app
COPY pnpm-*.yaml package.json pnpm-workspace.yaml turbo.json ./
COPY packages ./packages
COPY apps/web ./apps/web
RUN pnpm -C apps/web install --frozen-lockfile

FROM deps AS build
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm -C apps/web build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/apps/web/.next ./.next
COPY apps/web/package.json .
RUN corepack enable && corepack prepare pnpm@9.9.0 --activate && pnpm i --prod --ignore-scripts
EXPOSE 3000
CMD ["pnpm", "start"]
