FROM node:20-alpine
RUN corepack enable && corepack prepare pnpm@9.9.0 --activate
WORKDIR /app
COPY package.json pnpm-workspace.yaml turbo.json ./
COPY packages ./packages
COPY apps/worker ./apps/worker
RUN pnpm -C apps/worker i && pnpm -C apps/worker build
CMD ["pnpm", "-C", "apps/worker", "start"]
